"""
找出 ion-zh-CN.json 中值与英文源相同（未翻译）的条目，
聚焦桌面端 Cowork/permissions/mode/settings 等常见 UI 词。
"""
import json, re
from pathlib import Path

base = Path(r'C:/Program Files/WindowsApps/Claude_1.3883.0.0_x64__pzs8sxrjxfjjc/app/resources/ion-dist/i18n')
en = json.loads((base / 'en-US.json').read_text(encoding='utf-8'))
zh_path = Path(r'C:/Users/liukun/Desktop/chineseTwo/locales/ion-zh-CN.json')
zh = json.loads(zh_path.read_text(encoding='utf-8'))

# 值与英文完全相同 = 未翻译
untranslated = {k: v for k, v in zh.items()
                if k in en and v == en[k] and isinstance(v, str) and len(v) > 1}

# 聚焦关键词
keywords = [
    'permission', 'Permission',
    ' mode', 'Mode',
    'bypass', 'Bypass',
    'cowork', 'Cowork',
    'settings', 'Settings',
    'allow', 'Allow',
    'deny', 'Deny',
    'approve', 'Approve',
    'reject', 'Reject',
    'accept', 'Accept',
    'decline', 'Decline',
    'grant', 'Grant',
    'revoke', 'Revoke',
    'token', 'Token',
    'key', ' Key',
    'plan', 'Plan',
    'usage', 'Usage',
    'limit', 'Limit',
    'quota', 'Quota',
    'session', 'Session',
    'workspace', 'Workspace',
    'project', 'Project',
    'folder', 'Folder',
    'file', 'File',
    'chat', 'Chat',
    'message', 'Message',
    'model', 'Model',
    'thinking', 'Thinking',
    'search', 'Search',
    'attach', 'Attach',
    'upload', 'Upload',
    'download', 'Download',
    'copy', 'Copy',
    'paste', 'Paste',
    'delete', 'Delete',
    'remove', 'Remove',
    'rename', 'Rename',
    'create', 'Create',
    'add', 'Add ',
    'edit', 'Edit',
    'save', 'Save',
    'cancel', 'Cancel',
    'close', 'Close',
    'open', 'Open',
    'send', 'Send',
    'submit', 'Submit',
    'confirm', 'Confirm',
    'continue', 'Continue',
    'back', 'Back',
    'next', 'Next',
    'done', 'Done',
    'retry', 'Retry',
    'refresh', 'Refresh',
    'reload', 'Reload',
    'update', 'Update',
    'upgrade', 'Upgrade',
    'install', 'Install',
    'uninstall', 'Uninstall',
    'connect', 'Connect',
    'disconnect', 'Disconnect',
    'enable', 'Enable',
    'disable', 'Disable',
    'toggle', 'Toggle',
    'select', 'Select',
    'filter', 'Filter',
    'sort', 'Sort',
    'view', 'View',
    'show', 'Show',
    'hide', 'Hide',
    'expand', 'Expand',
    'collapse', 'Collapse',
    'pin', 'Pin',
    'unpin', 'Unpin',
    'star', 'Star',
    'share', 'Share',
    'export', 'Export',
    'import', 'Import',
    'archive', 'Archive',
    'restore', 'Restore',
    'duplicate', 'Duplicate',
    'preview', 'Preview',
    'publish', 'Publish',
    'unpublish', 'Unpublish',
    'report', 'Report',
    'flag', 'Flag',
    'block', 'Block',
    'mute', 'Mute',
    'invite', 'Invite',
    'join', 'Join',
    'leave', 'Leave',
    'logout', 'Logout',
    'login', 'Login',
    'sign in', 'Sign in',
    'sign out', 'Sign out',
    'sign up', 'Sign up',
    'get started', 'Get started',
    'learn more', 'Learn more',
    'see more', 'See more',
    'load more', 'Load more',
    'try again', 'Try again',
    'go back', 'Go back',
    'skip', 'Skip',
    'dismiss', 'Dismiss',
    'ignore', 'Ignore',
    'notification', 'Notification',
    'alert', 'Alert',
    'warning', 'Warning',
    'error', 'Error',
    'success', 'Success',
    'loading', 'Loading',
    'connecting', 'Connecting',
    'syncing', 'Syncing',
    'generating', 'Generating',
    'processing', 'Processing',
    'uploading', 'Uploading',
    'downloading', 'Downloading',
    'analyzing', 'Analyzing',
    'thinking', 'Thinking',
    'today', 'Today',
    'yesterday', 'Yesterday',
    'just now', 'Just now',
    'dark mode', 'Dark mode',
    'light mode', 'Light mode',
    'theme', 'Theme',
    'language', 'Language',
    'region', 'Region',
    'appearance', 'Appearance',
    'privacy', 'Privacy',
    'security', 'Security',
    'account', 'Account',
    'profile', 'Profile',
    'billing', 'Billing',
    'payment', 'Payment',
    'invoice', 'Invoice',
    'subscription', 'Subscription',
    'free', 'Free',
    'pro', 'Pro',
    'enterprise', 'Enterprise',
    'team', 'Team',
    'member', 'Member',
    'admin', 'Admin',
    'owner', 'Owner',
    'role', 'Role',
    'organization', 'Organization',
    'api', 'API',
    'webhook', 'Webhook',
    'integration', 'Integration',
    'extension', 'Extension',
    'plugin', 'Plugin',
    'tool', 'Tool',
    'agent', 'Agent',
    'task', 'Task',
    'run', 'Run',
    'log', 'Log',
    'history', 'History',
    'memory', 'Memory',
    'context', 'Context',
    'prompt', 'Prompt',
    'response', 'Response',
    'output', 'Output',
    'input', 'Input',
    'code', 'Code',
    'image', 'Image',
    'document', 'Document',
    'voice', 'Voice',
    'audio', 'Audio',
    'microphone', 'Microphone',
    'camera', 'Camera',
    'screen', 'Screen',
    'keyboard', 'Keyboard',
    'shortcut', 'Shortcut',
    'hotkey', 'Hotkey',
    'zoom', 'Zoom',
    'minimize', 'Minimize',
    'maximize', 'Maximize',
    'fullscreen', 'Fullscreen',
    'quit', 'Quit',
    'exit', 'Exit',
]

hits = {}
for k, v in untranslated.items():
    for kw in keywords:
        if kw.lower() in v.lower():
            hits[k] = v
            break

# 按长度排序，短的优先
short_hits = {k: v for k, v in hits.items() if len(v) <= 50}
print(f'Total keyword hits: {len(hits)}  (short<=50: {len(short_hits)})')
print()
for k, v in sorted(short_hits.items(), key=lambda x: x[1]):
    print(f'  {k}: {v!r}')
