import json
from pathlib import Path

path = Path(r"C:\Users\liukun\Desktop\chineseTwo\locales\ion-zh-CN.json")
data = json.loads(path.read_text(encoding="utf-8"))

updates = {
    "+XvhFRQllk": "将 settings.json 拖到此处",
    "/Yle6kJFht": "<b>按 {shortcut}</b> 输入给 Claude",
    "0e395A/3KF": "你可以随时在账号设置中取消。",
    "0miS7u3JX0": "设置",
    "1Vo908p7lJ": "使用特定语音和语气",
    "1e4bzV+hHI": "托管设置（settings.json）",
    "1wk34hxJE1": "已在设置中禁用",
    "2PX0a5yxRY": "Cowork 设置已更新。",
    "2QF7xrKrSb": "Cowork 要求通过现代安装程序安装 Claude Desktop",
    "2pBMB9dnRB": "+{count} 个更多连接器",
    "3RnDBBq8HJ": "在 设置 → 用量 中提高限制",
    "3ZjZM4Q0k0": "Cowork 聚焦插图",
    "41VRfQy78K": "它提供 {serverCount, plural, one {# 个连接器} other {# 个连接器}}。",
    "4dLJ2nJ6xe": "关闭设置",
    "4lWgUGlrk4": "推荐连接器",
    "55DTrwlixu": "保存设置失败",
    "5735ZQmOi4": "所有键盘快捷键",
    "5UZ7woP+0X": "受信任的 Cowork 文件夹",
    "6dIf/9B+Wq": "Cowork 试用",
    "6dqYnFDOYW": "发票",
    "6e3lKOj1rz": "邮件提供商设置",
    "71Ii8x+U/r": "支付发票",
    "72Si4CyWwi": "Claude Code Desktop 设置",
    "76aiFQ9/NE": "网页端 Claude Code 聚焦",
    "7HFalNigyO": "项目可帮助整理你的工作，并在多个对话中复用知识。上传文档、代码或文件来创建主题集合，Claude 可以反复引用。",
    "7Orkcosvv2": "快速访问快捷键",
    "7m24h8rpXP": "可在 Claude.ai、Claude Code、Claude Desktop 或第三方应用中使用额度。额度用完后，你可以添加更多额外用量以继续超过方案限制。到期时间：{date}。",
    "8JjaslSBQx": "组织设置",
    "8Q+Q5LuGum": "浏览连接器",
    "8mM8bURYje": "重新登录你的 {connectorNames} {count, plural, one {连接器} other {连接器}} 以获取最新更新。",
    "9+0Y1CW4+p": "更新 Cowork 设置失败。",
    "9/NIZHbeDd": "只使用来自你信任开发者的扩展。Anthropic 不控制开发者提供哪些工具，也无法验证它们是否会按预期工作或是否会发生变化。",
    "9EkCNB+/D5": "你能控制 DNS 和 SSO 设置吗？",
    "9aM6b8EJG/": "在 Claude Code 设置中启用",
    "9kg3aIjMKS": "记忆主题建议",
    "9oyFzI+Zy9": "此仓库尚未安装 Claude Code GitHub App。请安装以启用扫描。",
    "9z1SUK0pfj": "你的隐私选择",
    "AIrtBG4vgM": "让 Claude 查看你的屏幕并控制你的鼠标和键盘。",
    "APL9XCnYQZ": "使用语音模式",
    "ASeBF84Db6": "你的语音会话已过期。你可以开始一个新的会话。",
    "AW1LeQqU3c": "在设置中开启它，即可从手机向 Claude 派发工作。",
    "AfTuRrB4TT": "用户设置",
    "AvrvsYzH0a": "允许你的团队在 Claude Code Desktop 中绕过所有权限检查。启用后，Claude 将在不请求批准的情况下执行操作。让 Claude 运行任意命令具有风险，可能导致数据丢失、系统损坏或数据泄露（例如通过提示词注入攻击）。<link>查看安全使用的最佳实践</link>",
    "BModtOOHNX": "会话会使用你的 Claude Code 设置、CLAUDE.md 和技能触发。",
    "BabVfykaQR": "在 macOS 菜单栏中，打开 <b>开发者 → Conway</b>",
    "BeU0l6VZZN": "启用后，用户只能安装已添加到上方列表中的桌面扩展。",
    "BmozBym0Lo": "现在添加实验室成员，或稍后从设置中邀请他们。所有邀请都必须使用 <domain>@{emailDomain}。</domain>",
    "BwbZlzhj12": "{count, plural, one {# 个请求的连接器不在你的目录中，已被} other {# 个请求的连接器不在你的目录中，已被}}隐藏。部分功能可能受限。{link}",
    "C+tDyEMA8k": "无法保存信任设置。你可以重试。",
    "CGYHQsEDeX": "设置已保存，但启动目录同步失败。你可以使用上方的“立即同步”链接重试。",
    "CMIe+A/IUL": "此工件需要你组织中不可用的连接器：{names}。实时工件只能在同一组织内共享。",
    "DQNC38ETdp": "全局说明已移至“自定义”。请前往新的“自定义”页面管理你的记忆和偏好。",
    "DjvrGlkTYr": "包含 Cowork，以及：",
    "DnGTgssGUt": "删除设置",
    "E/nV5I+zT2": "在找桌面扩展？请在<link>这里</link>管理。",
    "E9os03b21x": "更新设置",
    "EM7LrzED1E": "保存 SCIM 配置设置失败。",
    "EW/tg2frt1": "所有第三方连接都记录在隐私政策中",
    "Esa62Eh0ZL": "Cookie 可能会收集用于在我们网站和其他网站上向你展示定制广告的信息。这些信息可能与你、你的偏好或设备有关。",
    "EvYhqmLu8E": "要启用此技能，请在设置中启用“代码执行和文件创建”",
    "EwEsCJ1zNM": "让 Claude 在你离开时处理任务。<link>Cowork</link> 现在作为研究预览在 Pro 中可用。",
    "F3KCJYlei2": "要在聊天中尝试此技能，请在设置中启用“代码执行和文件创建”",
    "F9axubrVEa": "前往设置以启用深度搜索",
    "FVgJ2SPFk7": "没有匹配的连接器。",
    "FY/hAgjuC4": "访问 Claude Code 时出现问题。请尝试退出并重新登录；如果问题仍然存在，请联系支持。",
    "FwfnnX911W": "使用语音转文字进行语音输入",
    "Fwhy1wAlHs": "你组织的 Claude in Chrome 设置中被屏蔽的网站将继续被屏蔽。",
    "G0hew2N8Cs": "赠送一周 Cowork",
    "G2josShxji": "免费试用 Cowork：同时运行多个任务，回来即可查看完成的工作。",
    "GHM/w3WPnr": "正在加载研究能力...",
    "Gohvo7uUA4": "在终端中使用 Claude Code 编写代码",
    "GuFiWblvU1": "技能已移至“自定义”。请前往新的“自定义”页面管理你的技能和连接器。",
    "H7onC7FL/y": "IP 允许列表设置已更新。",
    "HOXvVIzCjF": "派发通知已禁用",
    "HVWxdOWP2V": "你组织已禁用 GitHub 连接器。请在连接器设置中启用它以使用 Claude Security。",
    "HZp4wEGqGR": "未收到研究期间要启用哪些连接器的响应",
    "Hn6Qe/SoQs": "Cowork 说明",
    "HpPjBU3Pxr": "让 Claude 截图，并在你允许的应用中控制键盘和鼠标。",
    "HpaHMWCKIZ": "{title} 颜色模式",
    "HyWzYH08yU": "Claude 会记住此项目中跨对话的上下文。可在设置中关闭。",
    "I0HTnhb+h8": "从 Cowork 复制设置",
    "I2yRi/4th4": "有什么偏好吗？（例如：活泼、简洁、鲜艳色彩等）",
    "ITNcvbNGOj": "访问此网站已被你的网络出口设置阻止。你可以在<link>设置</link>中启用包管理器访问。",
    "Iy46CwcVFj": "现在添加队友，或稍后从设置中邀请他们。所有邀请都必须使用 <domain>@{emailDomain}。</domain>",
    "J0TtmaQphz": "限制你的团队可以在桌面上安装的桌面扩展。",
    "J4/1ZRQCuR": "查看连接器",
    "JMCprEaQR9": "设置已保存，但启动目录同步失败。你可以使用同步按钮重试。",
    "JVPgZliR/R": "Claude Code 是一个智能编码伙伴，理解你的代码库，并帮助你用自然语言编写代码。",
    "JZHDdE8h3s": "充分使用 Cowork，并获得比 Pro 多 5 倍的用量",
    "JgOfgIMudw": "你无权访问此组织，或它不满足 {clientName} 的要求。请联系组织管理员请求访问权限，或检查你的 Claude Code settings.json 配置。",
    "Jod6k4AK+8": "无法导出配置文件。",
    "KPzcJyA//+": "鼠标和键盘控制所必需。",
    "KS0bwV0zAX": "Cookie 设置",
    "Ka1nlhE/YQ": "Cowork 可能消耗较多用量。为获得最佳体验，建议<link>升级到 Max</link>。",
    "KlUfGZh83n": "插件可用于 Claude Code 和 Claude Cowork。此表单中的所有提交都会经过审核，以决定是否收录到插件市场。",
    "KqNLdIdRUj": "快速入口设置",
    "KuEUpEYp0D": "添加主题切换和与你现有颜色匹配的深色配色，然后检查每个界面区域以确保它能正确响应。如果你已有深色模式，则会审核是否有任何未正确切换的地方。",
    "L+ZlgoNn9D": "无法保存认证设置。",
    "L1FMUJphkl": "会话会使用你的 Claude Code 设置、CLAUDE.md 和技能触发。",
    "L33iCfJN33": "确认保留设置",
    "LLEGPTqKjN": "通过 Cowork，Claude 会将复杂任务拆分为并行工作流。",
    "LRJefnMZ6x": "这将为你组织中的所有用户禁用此功能。你可以随时从组织设置中重新启用它。",
    "M4wKXuEECA": "要远程继续会话，请在终端中的 Claude Code 里运行 /web-setup 来配置远程环境",
    "M6WeOmqos+": "此设备已禁用扩展目录。请联系你的 IT 管理员了解更多信息。",
    "ML2Fg1r7Jy": "你的组织当前已禁用 Cowork，但你仍可预先设置或清除监控设置。",
    "MOFrpaQyQU": "了解你的表达风格以及如何改进",
    "MTf73XTkKu": "安装将授予此扩展访问你电脑上所有内容的权限。显示的开发者信息未经 Anthropic 验证。安装前请确保你信任此扩展的来源。",
    "MV/Q21S7EF": "SSH 连接失败。你可以从环境下拉菜单编辑服务器设置，或<retry>重试</retry>。",
    "Moscfoce2M": "项目设置",
    "MrfbdXppxF": "使用 GitHub 认证失败。请确认 Claude Code GitHub App 有权访问此仓库。",
    "MtKXJKq5LA": "监控设置已更新。",
    "N1Cf7XEjX9": "你的管理员尚未启用此选项。请让他们在 组织设置 → Cowork 中开启。",
    "N36VeugT9x": "管理 GitHub Enterprise 设置",
    "N5boDujZT0": "更新 IP 允许列表设置失败。你可以重试。",
    "NPPnZiceNd": "通过桌面扩展释放 Claude 的更多能力",
    "NetAY1U905": "聊天、Cowork 和代码现在位于侧边栏中。",
    "NlixH3av58": "这将与<link>用户偏好</link>和聊天中选择的风格一起生效。",
    "O2GC7B73R7": "分享使用连接器的聊天",
    "OCeEG5E1gF": "个人偏好",
    "OCrc1dnIgW": "你账号的 <link>Claude in Chrome 设置</link>中被屏蔽的网站将继续被屏蔽。",
    "ODG8pmZXCB": "语音：",
    "OHd8hCivcJ": "GitHub 访问已禁用。请在<link>连接器设置</link>中启用。",
    "OMSDTsdd44": "Claude 将截取你的屏幕并控制你的鼠标和键盘。你需要批准每个应用，但不需要确认 Claude 执行的每一步。",
    "OYCQNmzhq8": "已启用分享使用连接器的聊天",
    "P8a4erIjxQ": "正在搜索连接器",
    "PEouamoWrA": "无法保存频道设置。你可以重试。",
    "PMtLjVeZxc": "允许成员创建持久 Cowork 智能体，它们可以控制电脑并自主处理任务。持久智能体可从同一账号已登录的任何设备接收指令，并可访问其电脑上的文件、应用和网站。",
    "POZDZ2sdGK": "未授予麦克风访问权限。请检查浏览器设置以允许访问。",
    "PRZrOGhThN": "直接从命令行运行 Claude Code。适用于任何 shell。",
    "Ps0CoiNXOT": "Cowork 任务",
    "QEYKwUWKyR": "查找符合偏好的公寓",
    "QIHuQ5JiKF": "允许成员与组织内其他人分享使用连接器的聊天。接收者会看到 Claude 的回复，但不会看到来自连接器的数据。",
    "QOGk2Uv1ia": "要生成此报告，Claude 将读取你最近在聊天、Claude Cowork 和 Claude Code 中的一部分对话样本。分析会在你的账号中运行，不会与组织共享。",
    "QWpaOHpLag": "网页端 Claude Code",
    "RHfDVjqmnh": "**编码与开发。** 你将能充分使用 Claude Code。",
    "RgBYOfF1vX": "个人偏好已移至“自定义”。请前往新的“自定义”页面管理你的记忆和偏好。",
    "RlL9/uN6lx": "更新域名设置失败。",
    "S4jlqK+Ks2": "加载扩展设置失败",
    "SF5bBtcIJu": "检查 Cowork 设置",
    "SOmoNTSHwn": "正在加载设置...",
    "T9mQEj6Yjy": "设置",
    "TWVZ9sOSIU": "Claude 可以在运行期间使用这些连接器中的所有工具（包括写入操作），而无需请求权限。请移除你不希望智能体访问的连接器。",
    "TarjusjO2m": "仅 Cowork",
    "TbIlgCOqPv": "更新 Claude in Slack 设置失败。",
    "TdwjO5Vmql": "指向你插件隐私政策的链接。Anthropic Verified 状态需要此项。",
    "TqGu1cw74U": "提交此支持请求即表示你确认，所提供的信息可能用于协助处理你的咨询并改进我们的服务。<link>隐私政策</link>",
    "U2glLvTvfJ": "此例程已自动禁用。请检查设置并重新启用。",
    "U7sSd9vqjv": "Cowork 支持用于监控和可观测性的 OpenTelemetry（OTel）事件。Cowork 通过 Claude Agent SDK 复用 <docsLink>Claude Code 的 OTel 事件架构</docsLink>。<learnMoreLink>了解更多</learnMoreLink>",
    "URCoGtVGuq": "你设定方向，Cowork 负责完成。",
    "UUBYJKQMzA": "访问 {hostname} 的网络已被你组织的网络出口设置阻止。遥测事件将不会导出。请在<link>网络出口设置</link>中添加它。",
    "UhPeL+5MP6": "<bold>跳过所有审批已开启。</bold>Claude 可以在不询问的情况下执行操作，包括使用连接器、浏览网页，以及控制你电脑上的应用。<link>查看安全使用提示</link>",
    "UzOHrWYM/0": "托管设置",
    "VFxpJYuBJP": "检测到架构错误。设置可能无法按预期工作。请查看 <link>Claude Code 设置文档</link>。",
    "VYtnXW5u3K": "网页端 Claude Code 需要 GitHub 访问权限。请在<link>连接器设置</link>中启用。",
    "VuEfHe2rAF": "此例程因配置不再有效而被禁用。请检查设置并重新启用。",
    "VwtAo17HDU": "在连接器设置中始终允许单个工具。",
    "WBvq3HlPae": "设置快捷键",
    "Wqq07hG4On": "设置网页端 Claude Code",
    "WtIr1E5UcX": "添加设置",
    "YYeFkrn6t3": "站点级权限继承自 Chrome 扩展。请在 Chrome 扩展设置中<link>管理权限</link>，以控制 Claude 可以浏览、点击和输入的网站。",
    "YcsTvupz/5": "关闭语音模式",
    "YeGDgoxCdD": "设置 Cowork 来交接任务，这样你可以专注于其他工作",
    "YuICcRAtEK": "打开开发者设置",
    "Z634GxacKG": "个人设置",
    "Z7a6vkGFmG": "你组织未启用 GitHub 连接器。请在<link>连接器设置</link>中启用它以连接 GitHub 仓库。",
    "ZD2vLszx9z": "自动重载设置已更新",
    "ZNQ/KiYXaG": "在浏览器设置中启用通知，以便在任务完成时收到更新。",
    "ZUirH2/k92": "创建默认云环境并控制 Claude 的网络访问。你可以随时在设置中自定义并创建新环境。",
    "aV2C0LVPvl": "更新浏览器扩展设置失败。",
    "ajNsXSoH3j": "电话提供商设置",
    "al7gzCbIR1": "导航到你偏好的目录，并运行以下命令以连接 Claude Code CLI",
    "avkhm8tb6Y": "无法访问麦克风。你可以检查浏览器设置后重试。",
    "b3c1n4ee56": "通过 Cowork，Claude 可以独立处理复杂任务。它可以整理文件、起草文档等。",
    "bIh93lfBpJ": "为代码和终端设置自定义等宽字体。该字体必须已安装在你的设备上。",
    "c9Uom7kDBR": "聊天、Cowork 和代码集于一个应用中。Claude 可以处理你的文件、应用和浏览器标签页。",
    "cDtj8ThZ98": "目录中没有可用扩展",
    "cIb9mcseDm": "已清除 Cowork 入门标记",
    "cNdxENxTHM": "Claude Code 现已提供桌面预览",
    "d0ngdkpbcb": "返回发布设置",
    "d4w+C9zAQh": "充分使用 Cowork，并获得比 Pro 多 20 倍的用量",
    "d5oLRD5Fub": "设置",
    "dMPLuwqN72": "此会话将在云容器中继续。本地 Claude Code worker 将断开连接，对话会在同一会话中继续。",
    "dO9dV+jFeZ": "前往连接器设置",
    "dQMhHY8Y8F": "开发角色档案",
    "dUfGMGn6Br": "更新设置失败。你可以重试。",
    "ddukRFJTDn": "Cowork 插图",
    "dfIVr8r8E6": "删除设置失败",
    "dlD/M9tHEO": "用量设置仅适用于 Pro 和 Max 方案。请升级以查看用量。",
    "e5N6FQA9NH": "允许使用你的聊天和编码会话来训练并改进 Claude。可随时在隐私设置中更改。<learnMoreLink>了解更多</learnMoreLink>",
    "eDHTgRaIJG": "Claude in Chrome 设置",
    "edWlt+5w83": "此设备已禁用桌面扩展。请联系你的 IT 管理员启用桌面扩展。",
    "f3JnPS+B3+": "概括描述",
    "f3kY6+YiOY": "显示第 {start}–{end} 个，共 {total} 个连接器",
    "fkNzoubYp3": "为整个组织定义权限、允许的目录等。这将覆盖用户和项目设置，并且仅适用于 CLI 和 IDE 中的 Claude Code。<link>了解更多</link>",
    "fqfZ7f+tjI": "更新 SSO 设置失败。你可以重试。",
    "g15SdUR6uf": "无效的网络出口设置",
    "gEN/pdWxkr": "Cowork 清单",
    "gLu6jzGeoR": "无法保存横幅设置。你可以重试。",
    "gmqgos5sJs": "可以管理组织设置中的用户角色",
    "guk10XyxXn": "更新监控设置失败。你可以重试。",
    "h4P9ubPLmp": "还允许连接器设置中未单独列出的任何 {cliName} 命令",
    "h8u1GJ6wFK": "添加技能以扩展 Claude 的能力。<link>了解更多</link>",
    "h9g8CcFgUJ": "删除托管设置",
    "hNvFMyByOO": "技能设置",
    "hqTrxTnjIg": "只使用来自你信任开发者的连接器。Anthropic 不控制开发者提供哪些工具，也无法验证它们是否会按预期工作或是否会发生变化。",
    "hts4ct5WaZ": "设置必须遵循 <link>Claude Code 设置架构</link>。无效设置可能会禁用你组织的 Claude Code。",
    "hxa88TRdij": "管理员可以在 设置 → 用量 中提高限制。",
    "xd436TVDRZ": "读取或解析 developer_settings.json 时出错：{error}",
    "DESQVjmxtx": "已禁用分享使用连接器的聊天",
    "DJTCdBsE3w": "要验证 {domain} 的所有权，请将以下 TXT 记录添加到你的域名 DNS 设置中：",
    "Y9ZdrJUzwo": "开启快捷键",
    "PNhE6qHSk3": "你的订阅已逾期，因此访问已暂停。要恢复访问，请更改付款方式并支付逾期发票。",
    "Rh5sEO+qAi": "这将删除你的所有数据（对话、项目、文件、记忆、设置），并降级到免费方案。你将被重定向到入门流程。确定吗？",
    "ZLWzKdwOaB": "你同意 Anthropic 将按上方金额每月定期从你的银行卡扣款，直到你根据我们的 {terms} 取消为止。你可以随时在账号设置中取消。",
    "HmOsjnFwIk": "扩展 {extensionName} {organizationText} 有可用更新。",
    "WIua8B+cb8": "无法使用系统对此类链接的默认应用打开链接。这通常是因为默认应用异常，或操作系统拒绝打开该链接。{url}",
    "aM9WCiUXzZ": "Cowork 当前不支持在搭载 {arch} CPU 的 {platform} 上运行",
    "gX/JCYf2fo": "Cowork 当前不支持在 {platform} 上运行",
    "hzmFz+zKgD": "当存在 <code>prompt</code> 时，你的设备可以返回响应：",
    "i6wCMcpNrS": "你已使用 {key} 与 Claude 说话，但 Claude 需要麦克风权限。",
    "jt3Lzr6Bu6": "信任 {directory} 并启动 Cowork 任务？",
    "odvvwvsA/1": "允许 Claude 在 {path} 中协作处理任务？",
    "rCO+ULu7rr": "扩展 {extensionId} 已被安全阻止列表拦截：{reason}",
    "tdoSuxb1IL": "由于以下错误，无法安装该扩展：{errorMessage}",
}

updated = 0
for key, value in updates.items():
    if key in data:
        data[key] = value
        updated += 1

path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"updated {updated} of {len(updates)}")
