import json
from pathlib import Path

path = Path(r"C:\Users\liukun\Desktop\chineseTwo\locales\ion-zh-CN.json")
data = json.loads(path.read_text(encoding="utf-8"))

updates = {
    "6HjndCURMx": "为组织中的所有用户自定义页面顶部显示的分类横幅。未设置时，将使用环境配置中的默认横幅。",
    "6JISQP9sUJ": "这是 Claude 与 {sharedBy} 之间聊天的副本。内容可能包含未经验证或不安全的内容，不代表 Anthropic 的观点。共享快照可能包含此处未显示的附件和数据。",
    "6Lto+Su3LN": "{email} 的更多操作",
    "6MV5l81liN": "所有槽位都在使用中，{queued, plural, one {# 个会话} other {# 个会话}}正在排队。请增加运行器数量，或等待会话完成。",
    "6OctzUG5hG": "欢迎加入 {orgName}",
    "6PfcnjvK6l": "你的应用需要但不应显示在代码中的 API 密钥和其他私密值。",
    "6RmAdlKFdq": "Anthropic 会在收到请求后及时删除你的数据，但安全违规或你通过反馈共享的对话除外。",
    "6Wj8Gjltbs": "已创建 PR",
    "6WwfTjrCl+": "已暂停。现有记忆会保留，但不会在新会话中读取或更新。",
    "6XFjk3vR/h": "为你的团队移除 {serverName}？",
    "6YrefCx4AJ": "适用于所有计划运行",
    "6ZBacUc8Qf": "移除服务器失败",
    "6ZDt71ZCiV": "编辑计划任务",
    "6bhBCcaBn8": "正在等待安全扫描完成。",
    "6eIovh5Zqn": "添加连接器",
    "6eZsxS9gAO": "{partnerName} 优惠：免费 {months, plural, one {# 个月} other {# 个月}} + {credit} 用量额度",
    "6gEPb8tW2V": "了解使用 Anthropic 产品时你的信息如何受到保护，并访问我们的 {privacyCenter} 和 {privacyPolicy} 了解更多详情。",
    "6gypIwnFmn": "为此实例恢复来自 Canvas 的 Claude 访问权限",
    "6ixvwr7lnO": "只有团队所有者可以管理此方案。",
    "6juXYmMRRM": "同步失败",
    "6jy/6dYXs0": "我们会在 {date} 将 {name} 的礼物通过电子邮件发送给 {toEmail}。你也会在 {fromEmail} 收到确认邮件。",
    "6knEErRogE": "访问受网络策略限制。请联系 IT 管理员。",
    "6l5vXQ1Gdi": "加载你的账号数据时出现问题。你可以重试或稍后再查看。",
    "6lylEpwTeZ": "随着目录变化自动添加或移除成员。你的组织会始终保持最新状态。",
    "6ntn9GcqBj": "使用 GitHub 创建项目",
    "6od6zLxPb4": "你的 AWS 注册令牌无效。请返回 AWS 产品页面，重新启动应用设置。",
    "6q2BMtlS+3": "{count, plural, one {# 个同步错误} other {# 个同步错误}}",
    "6rfB2VCG2W": "查看你的连接器",
    "6sFvtToIFL": "正在启动会话…",
    "6slcDzAMdt": "允许使用已验证域名邮箱的账号通过 SSO 登录。",
    "6t59kyKuT8": "点击此处确认购买额外用户席位，并确认 AWS Marketplace 可向你开具发票",
    "6tBv0vGN6N": "成员已移除",
    "6tCDO9haeM": "邀请链接已禁用",
    "6tFqImOTXj": "添加到此会话",
    "6tKFnFi35/": "{sign}{count, plural, one {# 个标准席位} other {# 个标准席位}}（按年折算）",
    "6up6/QgcGo": "你无法将 Anthropic Google 账号连接到 Staging 环境。",
    "6vCxM+Ada3": "输入或粘贴多个邮箱，使用逗号或换行分隔。",
    "6z060h/voc": "设置",
    "6zSoH3qYur": "编辑账单地址",
    "6zUqW/8hiB": "无需离开团队聊天即可交付代码。",
    "7+UPMnhJCX": "身份验证失败",
    "736gK8M6fa": "安装将授予访问 Cowork 可用全部内容的权限。",
    "772a2Sk1gY": "SCIM 目录同步",
    "78kIpAldlI": "{clientName} 想要连接到你的 Claude 账号",
    "7ATNnsYDg/": "失败",
    "7AiaJ2eB46": "下一张发票",
    "7JJSLX6Qhr": "此优惠需要有效的注册码。请检查你收到的链接，或联系合作伙伴获取新的注册码。",
    "7K5nqaF/na": "指向此 URL 的外部服务将无法再访问 Conway。\"{label}\" 将被永久移除。",
    "7LHqDwS9x7": "{clientName} 想要连接到你的 {orgType}{orgName}",
    "7NnERT1zuL": "在你的身份提供商中找不到的成员将从此组织中移除。",
    "7NrmWSpPNp": "包含 {previousPlan} 的所有内容，另外还有：",
    "7POMfMfi+y": "由 {author} 创建",
    "7Ph1BdGY9y": "重新连接你的 GitHub 账号以设置 GitHub 触发的例程。",
    "7QuO1abTDG": "允许团队成员使用聊天、项目和工件。",
    "7U9zIyEl4n": "在 3/3 个运行器上失败",
    "7boqgXFUkq": "创建新组织",
    "7eoDwJl17N": "有哪些安全风险？",
    "7fCBPXAUhO": "查看所有连接器",
    "7h4ngmaVvb": "你已达到会话限制 ∙ 将于 {time} 重置",
    "7hEuUsS9AF": "探索其他方案",
    "7ohV9/uIck": "启用上方技能以上传和管理组织技能。",
    "7rMutf2/jE": "描述你的连接器用途及其关键功能…",
    "7rtIkw4iT2": "你已登录",
    "7sjOZudIvX": "获取 Claude 应用",
    "7tjeNzKXED": "适用于任何已添加的插件",
    "7unK/QWHsu": "你正在接近方案限制。为避免工作中断：",
    "7vjLQqQEXk": "技能验证失败。你可以重试。",
    "7zmwLrWWY0": "它提供 {hookCount, plural, one {# 个钩子} other {# 个钩子}}，会在你的会话期间自动运行。",
    "807qgLdlHv": "向项目添加文件时出错",
    "8084V98I5l": "请让管理员启用额外用量以获得更多运行次数。",
    "80g19Nu67u": "在 GitHub 中查看",
    "80gn7FstL7": "此账号已禁用电子邮件登录。请选择其他登录方式。",
    "86+xwZ5Ijs": "创建 GHE 配置失败。请检查输入后重试。",
    "8Aa/HbeJSY": "违反条款或使用政策",
    "8FFnw6dtPw": "用户无需提供任何凭据即可创建会话。",
    "8FKQlV/toA": "加载共享内容时出错",
    "8HA8cAJL3s": "若按年计费，每席位/月。若按月计费，则为每席位 25 美元和 125 美元。最低 {minimumSeatCount, plural, one {# 个席位} other {# 个席位}}。",
    "8Kdy7zZ9Un": "无法暂停计划。你可以重试。",
    "8MpKuGKlmc": "你的管理员要求批准此操作。你仍然可以阻止它。",
    "8Nsys2V72+": "更新连接器分享设置失败。",
    "8O/kvCHwHy": "已创建 {skillName}",
    "8OZA8mL5V6": "比免费版更多用量*",
    "8PB5HK/lHX": "你的用量不受限制。如需帮助，请直接联系管理员。",
    "8PIpCwu25H": "邀请队友",
    "8QVkswwDPB": "使用此密钥部署运行器以开始提供会话：",
    "8SUqaEC0FX": "删除目录并禁用",
    "8T9PGQkYRT": "自动禁用：文件功能",
    "8TFSr6sl4m": "在适当时使用这些数据回应你的提示（例如总结我的收件箱）",
    "8WaKWzauH+": "启动代码会话",
    "8Wv92QC8Xj": "所有组织",
    "8XXYL7ma5x": "安装到 .claude.local/ — 个人使用，已被 git 忽略。",
    "8ZZduOA+Di": "单点登录（SSO）和域名捕获",
    "8czoqkxzFQ": "无法启动扫描会话。你可以重试。",
    "8dfzU9yNKx": "代码会话",
    "8eQ7FMdAHQ": "继续使用 GitHub",
    "8gGuBJNN9j": "Claude in Chrome 仅可在你下方允许的网站上使用",
    "8h5ytK0Usv": "使用 Claude 查找并修复代码中的安全漏洞。",
    "8nG6Bbqbcy": "查询已运行。未返回任何行。",
    "8ocabTDLrB": "从任何地方接续任意会话——浏览器、终端或移动端。",
    "8omDeBwCj8": "你输入了 <b>{initiatingEmail}</b>，但当前登录账号是 <b>{currentEmail}</b>。",
    "8qey23v8XD": "应用客户端 ID",
    "8qlQJW7dR/": "组织已创建，但无法加载。请刷新页面继续。",
    "8qzCpf4q7/": "继续即表示你知悉 Anthropic 的<privacyLink>隐私政策</privacyLink>。",
    "8rYr0NKw3D": "此会话来自私有仓库，可能包含安全凭据。任何拥有链接的人都可以查看它们。",
    "8rtOof2z1Y": "与耐心解释的伙伴一起边构建边学习编程。",
    "8u9/Ta/NxG": "限制组织中用户可为每个工具选择的权限级别。限制会设置上限——用户始终可以选择更严格的设置。",
    "8v6OV5rVY1": "已接受的代码行数",
    "8vKv7jYrZq": "正在检查更新…",
    "8w8g6qgplC": "添加应用",
    "8wJOnh9xCD": "聊天建议已禁用",
    "8xj4q+m7nM": "允许频道通知",
    "8y0mQ6q8Fh": "返回插件列表",
    "8zHywm06al": "Claude Security 需要 Claude Code 网页访问权限。请升级席位以启用此功能。",
    "8zM7Nid3ps": "插件仅可用于 Cowork 和 Code",
    "90ECyk5cir": "无法更新自动合并设置。你可以重试。",
    "919U2iN5aZ": "邀请队友",
    "91lG99kLu3": "删除环境失败。你可以重试。",
    "94L6irF0n9": "成员数量变更已按比例计算——旧数量会获得抵扣，新数量会按剩余账期计费。",
    "96Q7ksVM9R": "此应用想要将文件下载到你的设备：",
    "96rBugyPlh": "快速网页设置已启用",
    "97vnEjHI6Q": "组织",
    "9EM4cjQY2s": "邀请链接已启用",
    "9ETfN/j9gl": "没有结果 — 任务{status, select, failed {失败} stopped {已停止} other {已结束}}。",
    "9Ed7p0W4ZD": "没有可邀请的有效邮箱。",
    "9H+SmBx9q+": "更新插件失败。",
    "9IMjsytzdi": "上传文档、代码和其他文件到项目中，供 Claude 在聊天中引用。",
    "9KeLdAizkx": "新成员审批",
    "9MNSGBAYKP": "升级现有组织",
    "9OnxTqF29V": "权限分析器",
    "9QHy+wVPnn": "功能已禁用",
    "9Rrm/va4iT": "启用 Google 登录",
    "9SC27/oZiJ": "Claude 想要使用 {appName}",
    "9TvBKZ1Zmw": "复制会话链接",
    "9U4GqP6CFr": "<b>GitHub 和 Google Drive 等链接来源会被引用，而不是下载。</b>Claude 可以在需要时获取它们。",
    "9U64gLEIVo": "保存文本内容时出错",
    "9VQSbE/1G7": "你打算<format>如何使用 Claude？</format>",
    "9atcdvODth": "直接在你的代码库中构建、调试并交付。",
    "9cg9QS6Rw0": "上传失败。你可以重试。",
    "9iEUZavjVe": "额外 {count} 个 {tierLabel} {count, plural, one {席位} other {席位}}",
    "9jzKWHkC4X": "无法更新记忆设置。请重试。",
    "9kUJSG4bai": "添加插件",
    "9mEpIaBJPG": "此账号未获企业管理员批准",
    "9mNMhPpnT5": "此例程因计划频率超过每小时一次而被禁用。请选择较低频率的计划并重新启用。",
    "9mq4/xSGLy": "已达到令牌限制（此 {windowHours} 小时窗口内已使用 {used, number}/{cap, number}）。请联系 IT 管理员。",
    "9oQ0JkPwFY": "搜索风格",
    "9p2I00plmo": "启用对组织参与度指标的程序化访问。",
    "9tupOWWL5F": "需要所有者批准",
    "9x1mcjFvDM": "已禁用",
    "9yJaaDvq1t": "允许组织中的人员与他人分享聊天。",
    "9zueQ/Ijhz": "你的令牌已保存，但无法创建默认环境。你可以手动设置一个。",
    "A0D4UAG3Vu": "让 Claude 在你的聊天和 Cowork 会话之间记住信息。",
    "A2/3NOQcVg": "已收到 GitHub 事件",
    "A2IkY117Us": "卸载技能失败。你可以重试。",
    "A6m+PJb2BQ": "处理你的身份验证请求时出错。请尝试重新登录。",
    "A7N3XAy3OA": "你要从哪个竞争对手切换过来？",
    "ABf9wj7LhM": "创建、继续和删除你的对话",
}

updated = 0
for key, value in updates.items():
    if key in data:
        data[key] = value
        updated += 1

path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"updated {updated} of {len(updates)}")
