import json
from pathlib import Path

path = Path(r"C:\Users\liukun\Desktop\chineseTwo\locales\ion-zh-CN.json")
data = json.loads(path.read_text(encoding="utf-8"))

updates = {
    "RdOxaQTgbS": "你的管理员配置了 {count, plural, one {一个尚不存在于此电脑上的工作区文件夹} other {多个尚不存在于此电脑上的工作区文件夹}}：{paths}",
    "hOB0LegXn/": "创建工作区{count, plural, one {文件夹} other {文件夹}}？",
    "hzKMHWvM80": "重启以更新到 {updateVersion}",
    "jo1SFYmkSJ": "你的管理员限制了此处可使用的文件夹。已跳过 {skipped, plural, one {# 个文件夹} other {# 个文件夹}}。",
    "mtAOMWDDTh": "Claude 将拥有对 {path} 中文件的读写访问权限。",
    "oqcioCyuAP": "Claude 的安装似乎已损坏。请从 claude.com/download 重新安装 Claude 以使用此功能。",
    "s7EJA5V2XI": "版本 {currentVersion} → {newVersion}。是否要安装此更新？",
    "tkAZD2CTH1": "通过 Nordic UART Service 广播一个以 <code>Claude</code> 开头的名称。线上传输内容为 UTF-8 JSON——每行一个对象，并以 <code>\\n</code> 结尾。",
    "+1pcHyi+yy": "当用户询问价格或合同时，将其引导至销售团队",
    "+pvdlwHfk6": "滚动 24 小时内包含的例程运行次数。启用后，额外运行会使用额外用量。",
    "/84EZuBIXX": "编码会话用量是免费层级的 5 倍",
    "/8fG7YnSUb": "成员必须拥有 {domains} 电子邮件地址。",
    "/F3BARWVEw": "你的组织尚未提供插件。请联系你的组织管理员添加插件。",
    "/LzCz+T6Ti": "你的组织要求你使用特定账号登录。请退出并使用获准账号登录。",
    "/UoXLuqkgW": "使用你的 SSO 身份提供商向企业组织添加新成员。",
    "/VMIpOgAKB": "无法启用 PR 自动修复。你可以从 PR 卡片中开启。",
    "/gXsy9Mz/K": "SSO 不适用于此地址。",
    "/sB4jomZAf": "选择席位并输入付款方式。下方订单详情显示今天的收费。",
    "/u2RLZvWhD": "会话事件仅对 Anthropic 组织成员可用。",
    "/vmgoj4e01": "构建一个真正可以分享的有趣项目",
    "/zJfJBU+lY": "无法启动代码会话。你可以重试。",
    "0Jv5hCuJvf": "分享链接，让拥有已允许电子邮件域名的人员加入。",
    "0QR/nCdo8I": "继续使用个人账号",
    "0W5YgjOd8C": "灵活的共享用量",
    "0aycL/x+Z/": "组 → 角色映射",
    "0by8WKNyrw": "查看发票详情",
    "0c4rfj0Cro": "额外用量请求",
    "0iawVcXcq7": "添加角色映射",
    "0l1VK7o2N3": "支持的账单币种：{currencies}。结账将被阻止。",
    "0lmKIf9uGH": "切换组织",
    "0mkp6rxalw": "功能已被组织禁用",
    "0nXCMmUrgP": "聊天建议已启用",
    "0oV5oq7kjN": "你很快会收到一封电子邮件，其中包含设置组织的后续步骤。",
    "0pQDRhC/66": "分享此工件也会分享其关联的附件、文件和评论。",
    "0qbPplXqGp": "对外分享",
    "0r/9ANkloS": "已取消分享",
    "12IjJwJucD": "验证码",
    "14+jcDS33B": "已创建 {count} 个文件",
    "16so6WDlmV": "验证码失败。请重试。",
    "1CkZjOq6JZ": "你的用量分配尚未设置。",
    "1EAWqJ4k/r": "项目已创建",
    "1Fbv299mqM": "从 cli.github.com 下载",
    "1IH/ageCw2": "你无法创建账号",
    "1Oruk/L6h3": "合规 API 已启用",
    "1S063iMGos": "你的应用很快就会准备就绪",
    "1TZSLAGeUn": "对环境的更改将应用于新会话。",
    "1U/+Klpk5D": "重置记忆时出现问题",
    "1XqeYrbjxi": "付款未能完成。你可以重试。",
    "1Yk+dlV0dT": "插件可以使用你的凭据、文件和工具运行任意代码。只安装来自可信来源的插件。",
    "1ZSD73HVtH": "你的网络已被阻止访问 Claude。如需帮助，请访问 <link>support.anthropic.com</link>。",
    "1ZxriJUeah": "更新成员失败。你可以重试。",
    "1dBMFaZe94": "需要更新 {platform}",
    "1ecHvDvvFp": "文件夹不再存在。项目可能已被移动或删除。",
    "1iSGWnGxaP": "你的身份提供商未返回有效的电子邮件地址",
    "1j9180ECqv": "设置团队时出现问题。",
    "1k+ePszMp4": "同步错误详情",
    "1lasV9aLbo": "整理我的文件",
    "1lkTOnWfrw": "添加连接器失败",
    "1w10uHGydu": "下载所选插件",
    "2+VODHagkt": "添加自定义连接器",
    "2/I2SuSV6O": "更新市场失败。",
    "204nAyA2MM": "SCIM 同步",
    "21lgr39Bvb": "重新安装应用",
    "23k/9oWRYP": "移除工具审批失败。你可以重试。",
    "23tEpu9S7F": "关闭额外用量失败",
    "25UPQz06h5": "启用派发通知失败。",
    "26SvXGZRRO": "正在重置…",
    "27kzpfn0z3": "复制插件失败。你可以重试。",
    "2BTdH3E2Bn": "设置登录",
    "2CSld7OPqp": "自定义你的组织看到的内容",
    "2FuQjAui2U": "登录验证码",
    "2Is6vg4wsB": "你组织的 IT 策略阻止创建新团队。请联系管理员。",
    "2LpCuHCDlI": "组织中最常用的技能",
    "2MsIKxrOyy": "{count, plural, one {# 次下载} other {# 次下载}}",
    "2P8WnPChl6": "检测到 Teams 账号",
    "2UNtCWqcOS": "删除会话失败。你可以重试。",
    "2WtTIWx05Q": "扩展“{extensionId}”的操作“{action}”（尚未实现）",
    "2Yo7y6360A": "确认登录",
    "2b+XMaMHUB": "Claude 处理权限决策",
    "2b9HRfhLmX": "上次运行失败",
    "2bv+rpYCtw": "由你的组织管理的插件将显示在这里。",
    "2bzEkW1TC5": "在你的 GHE 实例中创建 OAuth App，并使用回调 URL：{callbackUrl}",
    "2cFRJvFAgY": "创建团队账号",
    "2d4J+BFU/w": "由你的组织管理 — 只读",
    "2dVMhn//gw": "此连接器存在服务器配置问题。请联系连接器提供方。",
    "2dXigF1Pil": "添加连接器",
    "2gnKy+cBQK": "邮政编码",
    "2oMyls6Wfx": "为 {pluginName} 设置连接器",
    "2pzxxHyNvM": "你的账单国家/地区需要不同的付款区域。请更新地址后重试。",
    "2qrY9Dcl6P": "插件已保存，但技能/命令同步失败",
    "2quuFTad/n": "控制连接器工具在新对话中的加载方式。",
    "2sy2QUzqHO": "规划组织结构",
    "2uUh88SA9g": "分享你的想法…",
    "34J8Grxmd1": "项目已删除",
    "37uJZ/IwAD": "向管理员请求访问权限",
    "3A0alDWIaf": "允许团队成员处理使用外部来源数据的工件。",
    "3AryFa8L4s": "拒绝所有 Cookie",
    "3G1YQdzzXu": "域名验证已移除。",
    "3GKlniy+z1": "上次扫描失败",
    "3H6X/TaynY": "正在搜索连接器…",
    "3IQY7sM0gL": "只有使用这些域名电子邮件地址的用户才能被邀请加入你的组织。移除域名不会影响现有成员。",
    "3U9XuVxC1Y": "SCIM 会直接从你的身份提供商同步成员列表。未在 IdP 中分配给此应用的成员将从组织中移除。",
    "3WKlYlcDGA": "组织插件",
    "3X8UX+uQxU": "聊天分享已启用",
    "3ZMclN3S73": "你的电子邮件域名与组织不匹配",
    "3cNJSty9kF": "被拒绝的应用",
    "3h6Nx0KOpC": "{count, plural, one {已删除 # 个聊天} other {已删除 # 个聊天}}",
    "3jjnGOuIFY": "创建上游凭据失败。请检查输入后重试。",
    "3nQ3fk1PnC": "{count, plural, one {# 项检查失败} other {# 项检查失败}}",
    "3p2Q7ASEHK": "Claude 将以 Claude GitHub App 机器人的身份创建 PR，而不是使用你的个人 GitHub 账号。",
    "3so7YsTKsw": "很抱歉，<bold>{clientName}</bold> 连接仅适用于 Claude.ai 付费账号",
    "3taIdsUUvN": "输入你的工作邮箱即可开始。我们会向你发送登录链接。",
    "3uJFznoUmn": "更新成员邀请设置失败。你可以重试。",
    "3xmoDkCUN0": "为你的团队启用记忆",
    "3xzrSOUVia": "删除计划失败。你可以重试。",
    "41i3U4xfU1": "你的账单地址已更改。请更新付款方式后重试。",
    "43D5uv51my": "{count, plural, one {移动 # 个聊天失败。你可以重试。} other {移动 # 个聊天失败。你可以重试。}}",
    "43X1YULJzA": "批准 Claude 的方案并开始编码",
    "4Cj4bScwnt": "读取 SCIM 用户和组信息",
    "4Eyg6psDkw": "正在搜索连接器…",
    "4IM6LUhKGZ": "自动同步现在需要 Webhook。请设置一个 Webhook 以继续接收插件更新。",
    "4KbD5KNrVM": "发生意外错误。<link>联系支持。</link>",
    "4O0Q0stVZE": "你可能已收到一封需要批准付款的电子邮件。如果不是这样，你可以<link>联系支持</link>。",
    "4WhhwM2FSY": "重置 Cowork 试用状态失败。",
    "4YeKYJfOnO": "点击此处确认购买额外用户席位，并确认 Anthropic 可按上述方式向你开具发票",
    "4eIHICfKCI": "删除风格失败。请重试。",
    "4fO3xPbsn4": "赠送朋友一周免费的 Cowork。如果对方喜欢并订阅，你将获得 {rewardAmount} 的额外用量。<termsLink>条款适用</termsLink>",
    "4gajh1u+my": "添加连接器失败。你可以重试。",
    "4kNppIYdpt": "你的连接器",
    "4m/FLB3Fd/": "来自团队负责人的消息",
    "4qtqYNaMyi": "关闭缩短会话长度",
    "4rjrK+BUVA": "此名称将显示在你的发票上。",
    "4suoYkIuEm": "从项目中移除聊天失败",
    "4xkhgPGjA+": "正在创建新组织",
    "4yIgsdRHmz": "{organizationName} 的所有人",
    "5+9UwuNuLM": "代码行数",
    "5/K8NDKvVv": "阅读我们的<securityLink>安全指南</securityLink>以了解更多信息。",
    "51mn5Bsftk": "允许团队成员彼此分享技能。",
    "52LXG0+owQ": "你可以设置 {target} 每月可用于额外用量的最高支出金额。",
}

updated = 0
for key, value in updates.items():
    if key in data:
        data[key] = value
        updated += 1

path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"updated {updated} of {len(updates)}")
