import json
from pathlib import Path

path = Path(__file__).resolve().parent.parent / 'locales' / 'ion-zh-CN.json'
data = json.loads(path.read_text(encoding='utf-8'))

translations = {
    # A
    'HkC5P+6HLi': 'AI 智能体',
    'xwEc8KM8zK': 'API',
    'SOIaY76szk': 'API 错误',
    'QWixthTELs': 'API 平台',
    'llYF6LEh34': 'API 请求',
    '4ryGIk6sQ8': 'API 范围',
    'L1RmsfNEEE': '关于 Anthropic 面试官',
    'mzc/4XeUay': '关于群组映射',
    'jfo6/1XVry': '关于项目存储',
    'zO1984hzMN': '操作模式',
    'SPBnT2clve': '正在激活研究模式...',
    'jg6O5D/kSD': '活跃会话',
    'wGcWboPWPh': '活跃任务',
    'A3Ey2O2gs2': '无广告对话',
    'k6cnrKqVVi': '无广告对话：',
    'Nvr5CeqKuU': '添加中...',
    'Gy3aQGlAJQ': '额外费用：',
    'NeEQBwkAvY': '附加功能',
    'gh/lBJ3ybG': '附加信息',
    'iDWlHzm7XW': '需要额外设置',
    'xBrtnx/FXj': '地址',
    'lmMQUEPXAt': '调整自动重载',
    'CA43KsJQwh': '调整限制',
    '1W/f1nmZs/': '调整用量',
    'iHN12uxiqf': '管理员',
    'V72EhnbTFu': '高级设置',
    'zhoVUTQ8Nb': '高级设置',
    'QGVI63s1dJ': '智能体',
    'GBnvl1JpeB': '智能体',
    'bC9979Pv0w': '即将完成...',
    'xvEaun0GGh': '始终显示最新版本',
    '3VG8rbxa4v': '发生未知错误',
    'FFJy9Pgt4P': '认证过程中发生未知错误。',
    'djFcx3krDh': '分析 Google Drive 文档',
    'e1Y2iXeKQ2': '分析客户反馈',
    'r3xR9e5TXy': '分析文学主题',
    'ZR58oaN4JJ': '其他 AI 产品更适合我的需求',
    '4ReZQ79dW+': '还有其他反馈吗？',
    '8aW1mhjPCF': '应用未安装',
    'eufK6+n0Ub': '即将达到会话限制',
    't2T1PWD6TI': '即将达到每周限制',
    'nFa1MsHw4R': '审批',
    'WCaf5CZSTt': '批准',
    'qbXbBIixhT': '自动批准',
    'm/7+82LTth': '自动批准（即时）',
    'Ln8ciHiZMb': '自动批准未来请求',
    '6XFO/Cw7Ld': '已批准',
    'Z/DKbn2gfH': '请求权限',
    'GkOEztGVgI': '关联会话',
    '1rMFg0JQMQ': '审计日志',
    '57VhQbitLE': '认证错误',
    'I3zX4u2bAN': '绕过认证',
    'Fh0QP1M2C8': '认证成功',
    '1MGe1NItau': '自动确认手机',
    'oKQHGunEG3': '已自动禁用',
    'c3OpeJZEwK': '已启用自动合并',
    'bQwn0jV5vW': '自动将会话整理到项目中',
    'sHRXIdTx3F': '自动重载',
    'Fvcg75HZwF': '自动重载已禁用',
    'JTSyIVn+xw': '自动重载已启用',
    'unT/B/rqrN': '自动重载已关闭',
    'C0IHaxOPo4': '余额不足时自动重载',
    'qQHsVqEort': '自动化浏览器任务',
    '7StJBCedWA': '已自动禁用：{features}',
    'V7E5rZnr7P': 'Claude 自主任务',
    'tM90hqjWj0': '等待输入',
    'UuJhXMxSMS': '背景动画',
    # B
    'CMansqNBPw': '背景颜色',
    'mtIIl7P3WD': '银行转账',
    'AwA0j/UFB/': '横幅设置已保存。',
    'Wfk3Mut5XF': '横幅文字',
    'U/my45Rm4s': '已列入黑名单',
    'AHk/hh2tts': '取消中...',
    '5kfntb9RKU': '取消',
    '3wsVWFbC1x': '已取消',
    '90evMzS2tV': '取消中...',
    # C
    'k2CQOVj6Q/': '无法连接到 Claude',
    'DIwdjQ8d2a': 'Claude 桌面版',
    'MwY0j6lAfZ': 'Claude 企业版',
    'HALZF/VbRH': 'Claude 免费版',
    'PEXDsCWhYl': 'Claude Max',
    'SIgPaVikdi': 'Claude 专业版',
    'k12Nonr/xR': 'Claude 团队版',
    '72Si4CyWwi': 'Claude 代码桌面设置',
    'pKPzBGJPRn': 'Claude 代码聚焦',
    'lsXtwu+DyQ': 'Claude 已完成回复',
    'I6AR9sgEDr': 'Claude 从不丢失上下文',
    'SB9OnyeeQf': 'Claude 合作伙伴网络',
    'IYcY9mG0+8': 'Claude 的选择',
    'rhd0P/pkRr': 'Claude.ai',
    'bCwEkBmYEv': 'Claude.ai（网页版）',
    'f+7mxeVUNe': 'Claude.ai 组织',
    '3AKEX/QMCE': 'Claude.ai 组织',
    'AkXGCFumOh': 'Claude Cowork',
    'Fo2tzWOJzu': 'Claude API',
    'VGolWy/Z96': 'Claude 平台',
    'jhys5B7SIQ': 'Claude（网页版）',
    'csr9dd5Yrj': 'Claude 已回复：{summary}',
    'zSxvfCOVEx': 'Claude {featureName}',
    'lxjxGdlvau': '错误率',
    'FFFScMMBYY': '错误率（30天）',
    'N01HT5JT7d': '（已编辑）',
    'yKEwi7f1HL': '（已取消）',
    'vg7ixeSm+z': '（未安装）',
    'dYdaV+VR+Z': '"{name}" 已创建。',
    'fBb7PGbjH8': '"{name}" 已启动。',
    'SiQUg3TgDt': '14 天免费试用',
    'Vg6ctp2T0e': '20 万上下文窗口',
    'kfTd44gfS5': '50 万上下文窗口',
    'Z53aXUf301': '：已禁用',
    'CwfAt4hy6H': '：已启用',
    'SPBnT2clve': '正在激活研究模式...',
}

updated = 0
for k, v in translations.items():
    if k in data:
        data[k] = v
        updated += 1

path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'Batch 1: updated {updated} entries')
