import json
from pathlib import Path

path = Path(__file__).resolve().parent.parent / 'locales' / 'ion-zh-CN.json'
data = json.loads(path.read_text(encoding='utf-8'))

translations = {
    'MZpd+6wFzC': '分析中',
    'EWw/tKINJT': '应用',
    '3n8o15PA9Q': '应用更改',
    'bZp/WPFEpx': '本地应用',
    'VR4TEVtcBD': '立即应用',
    '6DN2BwXOYy': '作为上下文附加',
    'qkN7P8fxeY': '作为上下文附加',
    'Hdtjhh1YnJ': '附加文件',
    'fe2GgpDxRl': '将消息作为上下文附加',
    'q79ToqmdbE': '音频设置',
    'Ladz5W7h+I': '缓存已清除',
    '0k74NW7Q7D': '缓存已清除。',
    'YrswiNGz88': '折叠文件夹 {name}',
    'eOJ4QUCTXl': '折叠侧边栏',
    'G6WKbR76ah': '折叠 {name}',
    '6q3tCnkd2h': '连接中',
    '5y2qWOlFVf': '连接中...',
    '4JvX9ZTEQB': '上下文窗口',
    'p556q3ugKt': '已复制',
    'p556q3uvbn': '已复制',
    'y1X1ZRLitc': '已复制为表格',
    'U8C1mTauzq': '已复制为文本',
    'ZClD7Suniq': '已复制文件路径',
    'Sjo1P40Dgp': '自定义',
    'Sjo1P44FYy': '自定义',
    'DIk4mwZHqI': '自定义 MCP',
    'QrhIREWrLd': '自定义智能体',
    'LkOy+yARuQ': '自定义限制',
    'KQvWvDRI1B': '已删除',
    'MM7OHMBA9j': '已删除一个文件',
    'TKl9hTsU6V': '已删除群组',
    'FZeQlcp+xX': '已断开连接',
    'dOQCL8n7dZ': '显示名称',
    '86Gv/DR1uA': '文档',
    'wmirkPk7bp': '文档',
    'erUYNPwVWB': '正在下载依赖...',
    'RanLi3PXWa': '正在下载更新...',
    '8gdscs3yJj': '下载中...',
    '8a1Ts60z9o': '空文件夹',
    'CDLJ0Wjq0x': '企业版',
    '0h/2FwRZQr': '错误',
    '96iMiC11cz': '错误',
    'KN7zKn8z4F': '错误',
    'zCIK9K8J4a': '错误',
    'TNJp26SJsW': '完成认证时出错',
    'I0XuBhEooS': '启动认证时出错',
    'zwTmNQr7gL': '检查要求时出错...',
    'fes7nfwp3b': '下载 PDF 时出错',
    'WL3FdCcP2y': '保存说明时出错，请稍后重试',
    'yam8nOrqOW': '提交支持工单时出错，请稍后重试',
    'eLzspFmHkT': '更新项目时出错，请稍后重试',
    'qLGRwgS/hL': '退出游戏',
    'ItG+wlzX/s': '退出隐身模式',
    'jnlKEhdBhF': '退出演示模式',
    '0oLj/toqZk': '展开',
    '3fObVXG3MP': '展开文件夹 {name}',
    'sGOTrQY3mW': '展开上方行',
    'fcUlh6WJ2V': '展开下方行',
    '3wVEAOPX5O': '展开导航',
    'gqupQTNMYN': '展开 {name}',
    'HGdgPPM2Ry': '解释',
    'DD7vnjM3m/': '简单解释一个复杂话题',
    'DcD966yJAY': '解释一个编程概念',
    'tf1lIh/bri': '免费',
    'd4igGebgUv': '正在生成选项...',
    '52pgl8yj7c': '正在生成摘要',
    'FmlC4WcPng': '发票已创建',
    'mZM6fcTXUG': '发票已发送',
    'mFYgAXM/x4': '更少',
    'M59JhXXku8': '手动',
    'Bzy/54I5zQ': '仅手动',
    'vErdXkZBiq': '仅手动',
    '2nz+k9xHZw': '稍后再说',
    'TuSL+ZooiG': '最小化',
    'TJEhp8h+U3': '更多 Claude 模型',
    'hDJDN/auqH': '更多详情',
    'HOsSgXORHL': '更多信息',
    '9yxvA9+l6B': '更多模型',
    '6UJqvNfJs2': '更多导航项',
    'IzCVhGdYVc': '更多选项',
    'WDBdrgEGU2': '更多选项',
    'oUWADlOjJt': '否',
    'FygPlH/oox': '无需 Anthropic 账号',
    'bnMqMr2Qwq': '无变化',
    'GK/ypt/bUL': '无更改',
    '8/nYCRMZAy': '未配置云环境',
    'NtkqiHex3n': '未找到目录',
    'dtM4xw3t5Q': '未找到表情符号',
    'L/OMRJA5D9': '永不过期',
    'GS4b/M3efZ': '未找到文件更改',
    'z6L6tQBOr9': '无文件更改',
    'zreH4pXxYz': '未找到文件',
    'iPWC3QiC9B': '无文件夹',
    'rlZCgj3vEq': '无群组',
    'lnWi+/6FQ/': '未检测到群组',
    'IXEHJguopN': '未找到群组',
    'ImFcQvTki8': '未找到群组。',
    'YeS7phazuq': '未找到图片',
    'PfW4AIIF4e': '无限制',
    'wLCEuvbSge': '无匹配项。',
    'YgoQMf/8DX': '无匹配文档',
    'q+uBnWx4Cq': '无匹配文档。',
    'IV/+/51PZA': '无匹配文件',
    'AcYkw67BeD': '暂无记忆',
    'xc7r0SA6rC': '暂无消息。',
    'ni1Q/RDeLh': '未找到组织',
    'DyoXiEr2fN': '无输出',
    'aFUEsXIPKo': '未找到支付方式',
    'I9pIGMJ8eG': '未提供支付方式',
    'u1zp+cKrUr': '未找到项目',
    'hXbm3QO8x3': '未找到项目。',
    '6DBpHaBrzp': '无限制',
    'l+z+kd3rdX': '暂无计划任务',
    'tb9rWAryya': '暂无例程。',
    '9zutKz3pwT': '暂无运行记录。',
    'qa1G/QUvqu': '暂无计划任务',
    'Lrl5Trz+z3': '暂无计划任务。',
    '6Z9ZhagoSD': '无会话限制',
    'tkKKAr63Bg': '无会话',
    'JgXnsChAXx': '未找到会话',
    'KqE7GJqcEk': '暂无会话',
    'tDaDof+rcN': '无需设置',
    'TMeenHCszI': '无快捷键',
    'yWSiuEkfbY': '未找到来源',
    'NmCRHK7Fm4': '暂无来源',
    'tVqP+rhco5': '无子目录',
    'ZXH44sMrF0': '暂无任务',
    'qSE8DDhMi7': '暂无任务。',
    'c+JYNI/sAV': '不了，谢谢',
    'YkHKEmiZL+': '暂无工具调用',
    'NLgFjnBrJo': '暂无内容。',
    'kAEQyVFWDv': '确定',
    'OvzONl52rs': '关',
    'U68RLSytvb': '开',
    'Zh+5A6yahu': '开',
    'HsVXDb0rpK': '已是最新版本',
    'NmK6zy4KAV': '付款',
    'qV+TFmE3ks': '付款失败',
    'BVTni9A2ca': '付款方式',
    'bHvyaZp1bm': '付款逾期',
    'puLNUJezx6': '固定',
    'Ek0ZOtz8EI': '固定为章节',
    '3f65Bv1/3o': '固定项目',
    'JJNc3cbYIJ': '上一个',
    'fb1a/oVcaa': '上一张图片',
    'd/JZabNLwR': '上一个匹配项',
    'eTNi1bQmuV': '上一个选项',
    'k9hDFZcH2E': '上一页',
    'kF7ScKKDd0': '上一张照片',
    'aXluVtf7Ei': '上一个问题',
    'XvzAaDqIQy': '上一个会话',
    'nZObrEhD3u': '上一个版本',
    'viXE3205/2': '私有',
    'R/eOkjWqNU': '专业版',
    'gmOpZEFvZz': '专业版（年付）',
    'CtoT+hDLer': '专业版（月付）',
    'd8e8oHn+vT': '专业版试用今日到期',
    'dewPQogr49': '正在处理图片',
    'mk92iTLBDN': '正在处理付款...',
    '6OWS4p9SXV': '处理中...',
    'uhu5aGgCHC': '公开',
    'xsXG0uXx+k': '公开项目',
    'QkdNrOPIP4': '公开项目已禁用',
    'ZxwCAl9MEV': '公开项目已启用',
    '137J1IwIEq': '重新连接',
    'dOGweUbyRk': '重新连接中...',
    '4VUYJNZzCo': '重新生成',
    '6PgVSeKg3s': '重新生成',
    'iXNbPfQDIZ': '重命名',
    'aSBYhpo0v4': '重命名群组',
    'e4WVRBWjEv': '重命名插件',
    'o96GILnoRP': '重命名会话',
    'x5Tz6MZH82': '举报',
    'BMYqsjhycd': '举报 URL',
    'mwPB1dkcoS': '报告已导出',
    'i+TY5eOB+b': '举报项目',
    'Nk3r7n0fmm': '举报会话',
    'zz6ObK7ZEM': '恢复',
    'FeM+9/s0gY': '恢复此版本',
    'fsB/4pdUqN': '已保存',
    'Xx0WZVz8QS': '发送消息',
    'OKhRC6eWRw': '分享',
    'E7GQdF/HSA': '分享并复制链接',
    'ptKsJgt3ja': '分享对话',
    'vifmGa4k1Y': '分享反馈',
    'PevoKxKMTm': '分享插件',
    'LxX3SmatkC': '分享项目',
    'AiWQ9FTazw': '分享会话',
    'hDI+JMUhFd': '排序方式',
    '9rVGvCDexf': '排序项目',
    'VwapsmdMes': '收藏',
    'IuZiap/Hqt': '收藏项目',
    'TRfaIL7S/7': '已同步',
    'eOnwqs6QFY': '同步中',
    'S92mvo6R0o': '同步中...',
    'AHQWDTo4+e': '思考中',
    'N7yS9DUvN4': '思考显示',
    'QrZMdiKa7h': '思考中...',
    'zWgbGgjUUg': '今天',
    'LXYYHhSmej': '将简报转化为设计项目',
    'opNVQCTN4x': '取消固定',
    'HElwNPiecu': '取消固定章节',
    'HhPHH3kNpx': '取消固定项目',
    'Y5zRLWgCMP': '取消收藏',
    'mZD5psf6pN': '取消收藏项目',
    'hsYvDX9WwB': '上传中',
    '1KtkFu0qP5': '正在上传附件',
    'JEsxDwhXPG': '上传中...',
    'mnJYBQZwb4': '语音',
    'rea9n5AU6A': '语音设置',
    'yQgeL20JNk': '语音快捷键',
    '3SVI5pV99B': '警告',
    'a5msuh5ORp': '是',
    '6dIxDP1C8c': '昨天',
}

updated = 0
for k, v in translations.items():
    if k in data:
        data[k] = v
        updated += 1

path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'Updated {updated} entries')
