import json
from pathlib import Path

path = Path(__file__).resolve().parent.parent / 'locales' / 'ion-zh-CN.json'
data = json.loads(path.read_text(encoding='utf-8'))

translations = {
    'ISly67nSyK': '同意',
    'gC6HyzeGoV': '同意并部署',
    'bF46uAWl+6': '按字母排序',
    'QWld+x6JhN': '替代方法：',
    'uScJvDfyGZ': '更改前始终询问',
    'VMIM8/fAKn': '分析',
    'HJv0iTm4zI': '分析',
    'ol94B0ISof': '分析数据集',
    'Xmz+hqJFU1': '分析 A/B 测试',
    'NoYszDBZks': '分析业务指标',
    'IQJwlJZkRw': '分析竞争对手',
    'vbeZYpbZRy': '分析行业趋势',
    '5MqrMLTlb6': '分析职位描述',
    '/BiZHS29Z7': '分析市场机会',
    '2C6TrW95uE': '年付',
    'osyYBn10tk': '年度总计',
    'ZSCbZACJ+n': '按年计费',
    'LftgYRq5hB': 'Anthropic',
    'L9aaTnFe5M': 'Anthropic 学院',
    'ttyT7kLLym': 'Anthropic 实验室',
    'Dr0UrrlbaC': 'Anthropic 联系人',
    '0KPI/TlIig': 'Anthropic 新闻',
    'WHcySsrbNk': 'Anthropic 兼容',
    '2rUVsUf259': '应用',
    'Ii8QbeXK1X': '应用名称',
    'D97Bn36m9Q': '仅限应用工具',
    'IqFP14lcA5': '已应用余额',
    'gRiKLfypim': '应用',
    'IzYUCGlYL9': '归档中...',
    'nc7BrwYVL+': '参数',
    'pgaCSv2/6H': '参数',
    'ZT0z9z6v6s': '询问',
    'KsA5dxbgQZ': '询问 Claude',
    '7JQzUua6iP': '询问 Claude 关于 {name}',
    'XfP/HbNKQz': '询问 Claude 任何问题',
    'AEustq5R+6': '由 Claude 自动整理',
    'rEBc+0T8zS': '扮演 Claude',
    'jg6O5D/kSD': '活跃会话',
    'wGcWboPWPh': '活跃任务',
    'eufK6+n0Ub': '即将达到会话限制',
    't2T1PWD6TI': '即将达到每周限制',
    'nFa1MsHw4R': '审批',
    'WCaf5CZSTt': '批准',
    'qbXbBIixhT': '自动批准',
    'm/7+82LTth': '自动批准（即时）',
    'Ln8ciHiZMb': '自动批准未来请求',
    '6XFO/Cw7Ld': '已批准',
    'Z/DKbn2gfH': '请求权限',
    'GkOEztGVgI': '关联会话',
    '1rMFg0JQMQ': '审计日志',
    '57VhQbitLE': '认证错误',
    'I3zX4u2bAN': '绕过认证',
    'Fh0QP1M2C8': '认证成功',
    'sHRXIdTx3F': '自动重载',
    'Fvcg75HZwF': '自动重载已禁用',
    'JTSyIVn+xw': '自动重载已启用',
    'unT/B/rqrN': '自动重载已关闭',
    'C0IHaxOPo4': '余额不足时自动重载',
    'qQHsVqEort': '自动化浏览器任务',
    'tM90hqjWj0': '等待输入',
    'UuJhXMxSMS': '背景动画',
    'CMansqNBPw': '背景颜色',
    'mtIIl7P3WD': '银行转账',
    'AwA0j/UFB/': '横幅设置已保存。',
    'Wfk3Mut5XF': '横幅文字',
    'U/my45Rm4s': '已列入黑名单',
    'AHk/hh2tts': '取消中...',
    '5kfntb9RKU': '取消',
    '3wsVWFbC1x': '已取消',
    '90evMzS2tV': '取消中...',
    'k2CQOVj6Q/': '无法连接到 Claude',
    'DIwdjQ8d2a': 'Claude 桌面版',
    'MwY0j6lAfZ': 'Claude 企业版',
    'HALZF/VbRH': 'Claude 免费版',
    'SIgPaVikdi': 'Claude 专业版',
    'k12Nonr/xR': 'Claude 团队版',
    '72Si4CyWwi': 'Claude 代码桌面设置',
    'pKPzBGJPRn': 'Claude 代码聚焦',
    'lsXtwu+DyQ': 'Claude 已完成回复',
    'I6AR9sgEDr': 'Claude 从不丢失上下文',
    'SB9OnyeeQf': 'Claude 合作伙伴网络',
    'IYcY9mG0+8': 'Claude 的选择',
    'csr9dd5Yrj': 'Claude 已回复：{summary}',
    'lxjxGdlvau': '错误率',
    'FFFScMMBYY': '错误率（30天）',
    'V7E5rZnr7P': 'Claude 自主任务',
    'AkXGCFumOh': 'Claude Cowork',
    'Fo2tzWOJzu': 'Claude API',
    'VGolWy/Z96': 'Claude 平台',
    'jhys5B7SIQ': 'Claude（网页版）',
    'zSxvfCOVEx': 'Claude {featureName}',
    'TJEhp8h+U3': '更多 Claude 模型',
    'hDJDN/auqH': '更多详情',
    'HOsSgXORHL': '更多信息',
    '9yxvA9+l6B': '更多模型',
    '6UJqvNfJs2': '更多导航项',
    'IzCVhGdYVc': '更多选项',
    'WDBdrgEGU2': '更多选项',
}

updated = 0
for k, v in translations.items():
    if k in data:
        data[k] = v
        updated += 1

path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'Batch 2: updated {updated} entries')
