"""
批量翻译：对所有值与英文源相同的短条目，
用内置翻译字典覆盖最常见的 UI 词汇。
"""
import json, re
from pathlib import Path

zh_path = Path(__file__).resolve().parent.parent / 'locales' / 'ion-zh-CN.json'
en_path = Path(r'C:/Program Files/WindowsApps/Claude_1.3883.0.0_x64__pzs8sxrjxfjjc/app/resources/ion-dist/i18n/en-US.json')

data = json.loads(zh_path.read_text(encoding='utf-8'))
en = json.loads(en_path.read_text(encoding='utf-8'))

# 精确值匹配翻译表（英文原文 -> 中文）
EXACT = {
    # 操作
    'Add': '添加',
    'Add member': '添加成员',
    'Add members': '添加成员',
    'Add note': '添加备注',
    'Add project': '添加项目',
    'Add tag': '添加标签',
    'Add to project': '添加到项目',
    'Add workspace': '添加工作区',
    'Adding...': '添加中...',
    'Admin': '管理员',
    'Advanced settings': '高级设置',
    'Agent': '智能体',
    'Agents': '智能体',
    'Agree': '同意',
    'Agree & Deploy': '同意并部署',
    'All': '全部',
    'All chats': '所有对话',
    'All files': '所有文件',
    'All members': '所有成员',
    'All models': '所有模型',
    'All projects': '所有项目',
    'All sessions': '所有会话',
    'All time': '所有时间',
    'Allow': '允许',
    'Allow all': '全部允许',
    'Already have an account?': '已有账号？',
    'Analysis': '分析',
    'Analyze': '分析',
    'Annual': '年付',
    'Annually': '按年计费',
    'App': '应用',
    'Apply': '应用',
    'Apply changes': '应用更改',
    'Apply now': '立即应用',
    'Approve': '批准',
    'Approved': '已批准',
    'Archive': '归档',
    'Archived': '已归档',
    'Archiving...': '归档中...',
    'Ask': '询问',
    'Ask Claude': '询问 Claude',
    'Ask Claude anything': '询问 Claude 任何问题',
    'Attach': '附加',
    'Attach file': '附加文件',
    'Audio': '音频',
    'Audio settings': '音频设置',
    'Auto': '自动',
    'Auto-reload': '自动重载',
    'Available': '可用',
    'Back': '返回',
    'Background animation': '背景动画',
    'Background color': '背景颜色',
    'Bank transfer': '银行转账',
    'Billing': '账单',
    'Block': '屏蔽',
    'Blocked': '已屏蔽',
    'Branch': '分支',
    'Branches': '分支',
    'Browse': '浏览',
    'Build': '构建',
    'Bypass permissions': '绕过权限',
    'Cancel': '取消',
    'Cancelled': '已取消',
    'Cancelling...': '取消中...',
    'Change': '更改',
    'Change model': '更改模型',
    'Change plan': '更改方案',
    'Changes': '更改',
    'Chat': '对话',
    'Chats': '对话',
    'Check': '检查',
    'Clear': '清除',
    'Clear all': '全部清除',
    'Clear cache': '清除缓存',
    'Clear history': '清除历史',
    'Clone': '克隆',
    'Close': '关闭',
    'Code': '代码',
    'Collapse': '折叠',
    'Collapse sidebar': '折叠侧边栏',
    'Comment': '评论',
    'Comments': '评论',
    'Complete': '完成',
    'Completed': '已完成',
    'Configure': '配置',
    'Confirm': '确认',
    'Connect': '连接',
    'Connected': '已连接',
    'Connecting': '连接中',
    'Connecting...': '连接中...',
    'Connection': '连接',
    'Continue': '继续',
    'Copy': '复制',
    'Copy link': '复制链接',
    'Copy message': '复制消息',
    'Copied': '已复制',
    'Create': '创建',
    'Create account': '创建账号',
    'Create project': '创建项目',
    'Create session': '创建会话',
    'Created': '已创建',
    'Custom': '自定义',
    'Dark': '深色',
    'Dark mode': '深色模式',
    'Data': '数据',
    'Default': '默认',
    'Delete': '删除',
    'Delete account': '删除账号',
    'Delete all': '全部删除',
    'Delete message': '删除消息',
    'Delete project': '删除项目',
    'Delete session': '删除会话',
    'Deleted': '已删除',
    'Deny': '拒绝',
    'Deploy': '部署',
    'Deployed': '已部署',
    'Description': '描述',
    'Details': '详情',
    'Disable': '禁用',
    'Disabled': '已禁用',
    'Disconnect': '断开连接',
    'Disconnected': '已断开连接',
    'Dismiss': '关闭',
    'Display name': '显示名称',
    'Document': '文档',
    'Documents': '文档',
    'Done': '完成',
    'Download': '下载',
    'Downloading...': '下载中...',
    'Draft': '草稿',
    'Duplicate': '复制',
    'Edit': '编辑',
    'Email': '邮箱',
    'Enable': '启用',
    'Enabled': '已启用',
    'Enterprise': '企业版',
    'Error': '错误',
    'Expand': '展开',
    'Expand navigation': '展开导航',
    'Export': '导出',
    'Failed': '失败',
    'Feedback': '反馈',
    'File': '文件',
    'Files': '文件',
    'Filter': '筛选',
    'Filters': '筛选',
    'Flag': '标记',
    'Folder': '文件夹',
    'Folders': '文件夹',
    'Follow': '关注',
    'Free': '免费',
    'Full screen': '全屏',
    'Generate': '生成',
    'Generating...': '生成中...',
    'Get started': '开始使用',
    'Go back': '返回',
    'Grant': '授予',
    'Group': '群组',
    'Groups': '群组',
    'Help': '帮助',
    'Hide': '隐藏',
    'History': '历史',
    'Home': '主页',
    'Image': '图片',
    'Images': '图片',
    'Import': '导入',
    'Input': '输入',
    'Install': '安装',
    'Installed': '已安装',
    'Installing...': '安装中...',
    'Invite': '邀请',
    'Invite members': '邀请成员',
    'Join': '加入',
    'Key': '密钥',
    'Language': '语言',
    'Learn more': '了解更多',
    'Leave': '离开',
    'Light': '浅色',
    'Light mode': '浅色模式',
    'Limit': '限制',
    'Link': '链接',
    'Load more': '加载更多',
    'Loading': '加载中',
    'Loading...': '加载中...',
    'Log': '日志',
    'Log out': '退出登录',
    'Login': '登录',
    'Logout': '退出登录',
    'Manual': '手动',
    'Max': '最大',
    'Member': '成员',
    'Members': '成员',
    'Memory': '记忆',
    'Message': '消息',
    'Messages': '消息',
    'Minimize': '最小化',
    'Model': '模型',
    'Models': '模型',
    'More': '更多',
    'More options': '更多选项',
    'Move': '移动',
    'Mute': '静音',
    'Name': '名称',
    'New': '新建',
    'New chat': '新建对话',
    'New conversation': '新建对话',
    'New message': '新消息',
    'New project': '新建项目',
    'New session': '新建会话',
    'Next': '下一步',
    'No': '否',
    'Notifications': '通知',
    'OK': '确定',
    'Off': '关',
    'On': '开',
    'Open': '打开',
    'Options': '选项',
    'Organization': '组织',
    'Output': '输出',
    'Owner': '所有者',
    'Password': '密码',
    'Paste': '粘贴',
    'Pause': '暂停',
    'Payment': '付款',
    'Payment failed': '付款失败',
    'Payment method': '付款方式',
    'Permissions': '权限',
    'Pin': '固定',
    'Plan': '方案',
    'Plugin': '插件',
    'Plugins': '插件',
    'Preview': '预览',
    'Previous': '上一个',
    'Print': '打印',
    'Privacy': '隐私',
    'Private': '私有',
    'Processing': '处理中',
    'Processing...': '处理中...',
    'Profile': '个人资料',
    'Project': '项目',
    'Projects': '项目',
    'Prompt': '提示词',
    'Public': '公开',
    'Publish': '发布',
    'Published': '已发布',
    'Quit': '退出',
    'Read more': '阅读更多',
    'Reconnecting': '重新连接',
    'Reconnecting...': '重新连接中...',
    'Redo': '重做',
    'Refresh': '刷新',
    'Regenerate': '重新生成',
    'Region': '地区',
    'Reject': '拒绝',
    'Reload': '重新加载',
    'Remove': '移除',
    'Rename': '重命名',
    'Report': '举报',
    'Reset': '重置',
    'Restore': '恢复',
    'Resume': '继续',
    'Retry': '重试',
    'Revoke': '撤销',
    'Role': '角色',
    'Run': '运行',
    'Running': '运行中',
    'Save': '保存',
    'Saved': '已保存',
    'Saving...': '保存中...',
    'Search': '搜索',
    'Security': '安全',
    'Select': '选择',
    'Select all': '全选',
    'Send': '发送',
    'Send message': '发送消息',
    'Session': '会话',
    'Sessions': '会话',
    'Settings': '设置',
    'Share': '分享',
    'Show': '显示',
    'Show all': '显示全部',
    'Show less': '显示更少',
    'Show more': '显示更多',
    'Sign in': '登录',
    'Sign out': '退出登录',
    'Sign up': '注册',
    'Skip': '跳过',
    'Sort': '排序',
    'Sort by': '排序方式',
    'Star': '收藏',
    'Start': '开始',
    'Status': '状态',
    'Stop': '停止',
    'Submit': '提交',
    'Subscribe': '订阅',
    'Success': '成功',
    'Summarize': '总结',
    'Sync': '同步',
    'Synced': '已同步',
    'Syncing': '同步中',
    'Syncing...': '同步中...',
    'Tag': '标签',
    'Tags': '标签',
    'Task': '任务',
    'Tasks': '任务',
    'Team': '团队',
    'Theme': '主题',
    'Thinking': '思考中',
    'Thinking...': '思考中...',
    'Title': '标题',
    'Today': '今天',
    'Toggle': '切换',
    'Token': '令牌',
    'Tokens': '令牌',
    'Tool': '工具',
    'Tools': '工具',
    'Translate': '翻译',
    'Try again': '重试',
    'Type': '类型',
    'Undo': '撤销',
    'Uninstall': '卸载',
    'Unknown': '未知',
    'Unpin': '取消固定',
    'Unstar': '取消收藏',
    'Update': '更新',
    'Update available': '有可用更新',
    'Updating...': '更新中...',
    'Upload': '上传',
    'Uploading': '上传中',
    'Uploading...': '上传中...',
    'Usage': '用量',
    'User': '用户',
    'Users': '用户',
    'Version': '版本',
    'View': '查看',
    'View all': '查看全部',
    'Voice': '语音',
    'Voice settings': '语音设置',
    'Warning': '警告',
    'Webhook': '网络钩子',
    'Workspace': '工作区',
    'Yes': '是',
    'Yesterday': '昨天',
    'Zoom in': '放大',
    'Zoom out': '缩小',
    # 状态/提示
    'Active': '活跃',
    'Inactive': '未激活',
    'Pending': '待处理',
    'Completed': '已完成',
    'Failed': '失败',
    'Expired': '已过期',
    'Paused': '已暂停',
    'Stopped': '已停止',
    'Online': '在线',
    'Offline': '离线',
    'Connected': '已连接',
    'Disconnected': '已断开',
    'Loading': '加载中',
    'Analyzing': '分析中',
    'Generating': '生成中',
    'Processing': '处理中',
    'Uploading': '上传中',
    'Downloading': '下载中',
    'Syncing': '同步中',
    'Thinking': '思考中',
    'Reconnecting': '重新连接',
    'Connecting': '连接中',
    # 权限相关
    'Ask permissions': '请求权限',
    'Bypass permissions': '绕过权限',
    'Actions mode': '操作模式',
    'Accept permissions': '接受权限',
    'Permissions mode': '权限模式',
    # 模型相关
    'More Claude models': '更多 Claude 模型',
    'More models': '更多模型',
    'Context window': '上下文窗口',
    'Thinking display': '思考显示',
    # 其他常见
    'Appearance': '外观',
    'Notifications': '通知',
    'Keyboard shortcuts': '键盘快捷键',
    'Keyboard shortcut': '键盘快捷键',
    'No shortcut': '无快捷键',
    'Font size': '字体大小',
    'Display name': '显示名称',
    'Just now': '刚刚',
    'Today at {time}': '今天 {time}',
    'Empty folder': '空文件夹',
    'No results': '无结果',
    'No matches': '无匹配',
    'Nothing here yet.': '暂无内容。',
    'No thanks': '不了，谢谢',
    'Maybe later': '稍后再说',
    'Try for free': '免费试用',
    'Get started for free': '免费开始使用',
    'Upgrade': '升级',
    'Upgrade plan': '升级方案',
    'Downgrade': '降级',
    'Manage plan': '管理方案',
    'Current plan': '当前方案',
    'Free plan': '免费方案',
    'Pro plan': '专业方案',
    'Team plan': '团队方案',
    'Enterprise plan': '企业方案',
    'Billing settings': '账单设置',
    'Payment settings': '付款设置',
    'Account settings': '账号设置',
    'Profile settings': '个人资料设置',
    'Privacy settings': '隐私设置',
    'Security settings': '安全设置',
    'Notification settings': '通知设置',
    'Language settings': '语言设置',
    'Theme settings': '主题设置',
    'General settings': '通用设置',
    'API settings': 'API 设置',
    'Integration settings': '集成设置',
    'Extension settings': '扩展设置',
    'Plugin settings': '插件设置',
    'Tool settings': '工具设置',
    'Agent settings': '智能体设置',
    'Model settings': '模型设置',
    'Voice settings': '语音设置',
    'Audio settings': '音频设置',
    'Display settings': '显示设置',
    'Accessibility settings': '无障碍设置',
    'Advanced settings': '高级设置',
    'Developer settings': '开发者设置',
    'Admin settings': '管理员设置',
    'Organization settings': '组织设置',
    'Team settings': '团队设置',
    'Workspace settings': '工作区设置',
    'Project settings': '项目设置',
    'Session settings': '会话设置',
    'Chat settings': '对话设置',
    'Message settings': '消息设置',
    'File settings': '文件设置',
    'Storage settings': '存储设置',
    'Cache settings': '缓存设置',
    'Network settings': '网络设置',
    'Proxy settings': '代理设置',
    'Connection settings': '连接设置',
    'Sync settings': '同步设置',
    'Backup settings': '备份设置',
    'Export settings': '导出设置',
    'Import settings': '导入设置',
    'Share settings': '分享设置',
    'Permission settings': '权限设置',
    'Role settings': '角色设置',
    'Member settings': '成员设置',
    'Invite settings': '邀请设置',
    'Webhook settings': '网络钩子设置',
    'API key': 'API 密钥',
    'API keys': 'API 密钥',
    'Access token': '访问令牌',
    'Access tokens': '访问令牌',
    'Secret key': '密钥',
    'Public key': '公钥',
    'Private key': '私钥',
    'Copy key': '复制密钥',
    'Revoke key': '撤销密钥',
    'Generate key': '生成密钥',
    'Rotate key': '轮换密钥',
    'View key': '查看密钥',
    'Hide key': '隐藏密钥',
    'Show key': '显示密钥',
    'Key name': '密钥名称',
    'Key ID': '密钥 ID',
    'Key type': '密钥类型',
    'Key status': '密钥状态',
    'Key created': '密钥已创建',
    'Key revoked': '密钥已撤销',
    'Key expired': '密钥已过期',
    'Key copied': '密钥已复制',
}

updated = 0
for k, v in data.items():
    if v in EXACT:
        data[k] = EXACT[v]
        updated += 1

zh_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'Bulk exact-match: updated {updated} entries')
