import argparse
import json
import re
from collections import Counter
from pathlib import Path

from common import ENCODING, ION_LOCALE_SRC, PROJECT_ROOT, resolve_apply_targets
from locale_backfill import DEFAULT_MESSAGE_PATTERNS, js_unescape


GROUP_RULES = [
    ("billing", re.compile(r"\b(bill|billing|checkout|payment|invoice|price|quote|plan|subscription|card|cost|sales|seat|trial|upgrade)\b", re.I)),
    ("claude-code", re.compile(r"\b(code|pull requests?|branch|git|worktree|session|shell|terminal|runner|repository|commit|review|launch|preview)\b", re.I)),
    ("privacy", re.compile(r"\b(privacy|Anthropic|diagnostic|metric|identity|account|conversation|provider|organization)\b", re.I)),
    ("plugins", re.compile(r"\b(plugin|skill|connector|extension|hook|agent|MCP)\b", re.I)),
    ("settings", re.compile(r"\b(setting|preference|notification|profile|avatar|font|theme|appearance)\b", re.I)),
    ("errors", re.compile(r"\b(error|failed|couldn't|cannot|invalid|denied|unavailable|blocked|rejected)\b", re.I)),
]


def classify_message(message: str) -> str:
    for group, pattern in GROUP_RULES:
        if pattern.search(message):
            return group
    return "general"


def extract_default_messages_with_files(assets_dir: Path) -> dict[str, dict]:
    messages: dict[str, dict] = {}
    for path in sorted(assets_dir.glob("*.js")):
        try:
            text = path.read_text(encoding=ENCODING)
        except OSError:
            continue
        for pattern in DEFAULT_MESSAGE_PATTERNS:
            for match in pattern.finditer(text):
                key = match.group("id")
                message = js_unescape(match.group("msg"))
                entry = messages.setdefault(key, {"defaultMessage": message, "files": []})
                if path.name not in entry["files"]:
                    entry["files"].append(path.name)
    return messages


def build_missing_items(messages: dict[str, dict], locale: dict) -> list[dict]:
    items = []
    for key, entry in messages.items():
        if key in locale:
            continue
        message = entry["defaultMessage"]
        items.append({
            "id": key,
            "defaultMessage": message,
            "suggestedGroup": classify_message(message),
            "files": entry["files"],
            "translation": "",
            "status": "todo",
        })
    return items


def write_markdown(items: list[dict], path: Path) -> None:
    counts = Counter(item["suggestedGroup"] for item in items)
    lines = [
        "# Missing Claude Locale IDs",
        "",
        "This file is generated by `scripts/extract_missing_locale_ids.py`.",
        "Unknown English should be translated here first, reviewed, then merged into `locales/ion-zh-CN.json`.",
        "",
        "## Summary",
        "",
    ]
    for group, count in sorted(counts.items()):
        lines.append(f"- `{group}`: {count}")
    lines.extend(["", "## Items", ""])
    for item in items:
        files = ", ".join(item["files"][:3])
        lines.extend([
            f"### {item['id']}",
            "",
            f"- Group: `{item['suggestedGroup']}`",
            f"- Files: `{files}`",
            f"- English: {item['defaultMessage']}",
            f"- Chinese: {item['translation']}",
            "",
        ])
    path.write_text("\n".join(lines) + "\n", encoding=ENCODING)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract missing zh-CN locale ids from current Claude Desktop JS assets.")
    parser.add_argument("--app-dir", help="Claude app directory. Auto-detected when omitted.")
    parser.add_argument("--output-json", type=Path, default=PROJECT_ROOT / "docs" / "missing-locale-ids.json")
    parser.add_argument("--output-md", type=Path, default=PROJECT_ROOT / "docs" / "missing-locale-ids.md")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    targets = resolve_apply_targets(Path(args.app_dir) if args.app_dir else None, auto_detect=True)
    messages = extract_default_messages_with_files(targets.assets_dir)
    locale = json.loads(ION_LOCALE_SRC.read_text(encoding=ENCODING))
    items = build_missing_items(messages, locale)
    payload = {
        "targetAssetsDir": str(targets.assets_dir),
        "defaultMessageIds": len(messages),
        "localeEntries": len(locale),
        "missingCount": len(items),
        "items": items,
    }
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding=ENCODING)
    write_markdown(items, args.output_md)
    print(f"missing ids: {len(items)}")
    print(f"json: {args.output_json}")
    print(f"markdown: {args.output_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
